version: "2.4"

services:
  postgres:
    image: postgres:latest
    container_name: emma_postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d test"]
      interval: 1s
      timeout: 30s
      retries: 50
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=emma
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_HOSTNAME=postgres
    networks:
      - db-manager
    volumes:
      - ./src/database/scripts/postgres-config.sql:/docker-entrypoint-initdb.d/postgres-config.sql

networks:
  db-manager:
