version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_HOST=postgres
    links:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - db-manager

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"
    networks:
      - db-manager
    volumes:
      - ./scripts/postgres-config.sql:/docker-entrypoint-initdb.d/postgres-config.sql

  db-manager:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: "sh -c 'npm install && npm run migrate:up'"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
      - POSTGRES_HOST=postgres
    networks:
      - db-manager
    volumes:
      - ./scripts/postgres-config.sql:/docker-entrypoint-initdb.d/postgres-config.sql

networks:
  db-manager:
